### ISSUE TITLE
intermittent loading indicator

### ISSUE THREAD

**Issue by moimikey** [adoppler/routes-loader#1]
is there a means to integrating a loading indicator with this loader? it would be a great option to be able to pass a component as a param to use, unless there's an alternative way that I can't seem to think of.

**Comment by adoppler** [comment]
No, nothing handles that specific use case at the moment.

If you want do show a loader while waiting for a chunk to load you could use the history prop passed down by react-router, something like:

```
class SiteLayout extends Component {

  state = {
    transitioning: false
  }

  componentDidMount() {
    this.props.history.listenBefore(() => {
      this.setState({ transitioning: true })
    })

    this.props.history.listen(() => {
      this.setState({ transitioning: false })
    })
  }

  render() {
    return (
        <div className={this.state.transitioning ? 'transitioning' : null}>
          {this.props.children}
        </div>
    )
  }

}
```

**Comment by moimikey** [comment]
thanks for the tip!
